### ISSUE TITLE
Audio Setup

### ISSUE THREAD

**Issue by oliverdunk** [GoogleChromeLabs/airhorn#17]
Hi,

Just wondering if there is an advantage to use an XMLHttpRequest for the airhorn sound effect rather than the native Audio API? I guess compatibility could be an issue, but it seems very well supported:
http://caniuse.com/#feat=audio

**Comment by PaulKinlan** [comment]
Good question, I was simply doing a fetch to stream in to the web audio
API.  I use the Web Audio to loop the sound a certain point.

**Comment by oliverdunk** [comment]
Do you think it'd be worth just using the Audio constructor which takes a URL as it's parameter? I'll happily PR that if you think it'd be better, but if it's not necessary than feel free to close this issue.

**Comment by PaulKinlan** [comment]
Let's keep it Open.  In the past the Chrome Service Worker stack on Andoird
could not handle audio elements.... It should be able to now but I need to
wait for the version to become a little bit more widespread.
