### ISSUE TITLE
Play horn when push is received via service worker

### ISSUE THREAD

**Issue by Elijax** [GoogleChromeLabs/airhorn#18]
I'm displaying desktop notifications when push requests come from GCM, but haven't succesfully played a sound when browser receives it, can you give me more information about how to achieve that...

Here is my sample:

``` javascript
self.addEventListener('push', function(event) {
    event.waitUntil(
        self.registration.showNotification("Title", {
            body: "body",
            icon: 'img/logo.png',
            vibrate: [200, 100, 200, 100, 200, 100, 200],
            requireInteraction:true,
            tag:"my-tag",
            sound:"notify.mp3"`,
            silent:false
        });
    );
})
```

**Comment by katul979** [comment]
When can we expect the support for sound attribute? Thanks.

**Comment by Elijax** [comment]
So, what alternatives do we have to achieve this operation when browser isn't active?

**Comment by arreumb** [comment]
Is there any other way to play a sound from a service worker when a push notification is received ?

**Comment by Satys** [comment]
Is there any update on this? When can we expect this feature? Again, is there any workaround?

**Comment by phalconjohy** [comment]
i need to click the notification on click function please suggest

**Comment by phalconjohy** [comment]
Notification.onclick = function(event) {	         
						   top.location=p_url;	
						   notification.close();	   
					} 

not supporting

**Comment by phalconjohy** [comment]
i need notification click on foreground

**Comment by vcfvct** [comment]
would be great if notification sound is supported, even just use the system(or browser) default first.

**Comment by schankam** [comment]
As of December 2018, looks like the sound attribute is not supported. It does not even appear in the specifications: https://developer.mozilla.org/en-US/docs/Web/API/notification

**Comment by jaipresto** [comment]
Unbelievably, there's still no simple/official way to make this work. Anyone know if progress is in the works? Anyone found any workarounds? If we're gonna make a petition, who's the recipient?

**Comment by MahmudulHassan85** [comment]
Hi Paul any update on sound attribute .

**Comment by agustin96** [comment]
so?

**Comment by DarKKnigHtdk16** [comment]
Still service worker Dont support sounds????

**Comment by RajatgGupta** [comment]
No support found for sound attribute in push notification.

**Comment by benson7667** [comment]
i really need a sound effect for web push notification. any workaround for this?

**Comment by celestemartins** [comment]
Why is it closed? any workaround?

**Comment by arnav-kr** [comment]
Woah this question was published in 2016 and it's about halfway 2021 still not supported its been 5 years 😑

**Comment by zju1** [comment]
Let's reopen this topic. We need an ability to play sound from push notification

**Comment by zju1** [comment]
Let's reopen this topic. We need an ability to play sound from push notification

**Comment by fshahmt** [comment]
Damn, seriously I was still in college when this issue was opened. No one cares, hot damn

**Comment by Santas** [comment]
+1

**Comment by valentinCorrea25** [comment]
"+ 1 probably there is a good reason for not being available, but lets wait for it !
