### ISSUE TITLE
Needs Visual Focus and Keyboard Access

### ISSUE THREAD

**Issue by normanbrobinson** [GoogleChromeLabs/airhorn#30]
Needs visual focus and keyboard access to cover minimal usability and accessibility use cases. Name role and state could be enhanced with aria role of button to improve those use cases.

**Comment by PaulKinlan** [comment]
Sorry I missed this. I think it's a good suggestion, will sort.

**Comment by PaulKinlan** [comment]
Added in 721ebf06d3f396019b58568ce90f6e309a25a156 and 5061261c00f08516a27fe4c9c2db5756e0639706 - what I have just noticed is that on desktop at least there is no visible highlight.
