### ISSUE TITLE
text color on splash screen unexplained

### ISSUE THREAD

**Issue by Focus3D** [GoogleChromeLabs/airhorn#36]
Hi,
tried to change the color of the text showing in the slash color but did not find any explication:
default : with “background_color”: “#2196F3”  in manifest.json
![screenshot_2018-01-25-17-28-14](https://user-images.githubusercontent.com/1816969/35399650-68f62556-01fd-11e8-8720-cdebb787ede9.png)
edited : “background_color”: “#FFFFFF” in manifest.json
![screenshot_2018-01-25-18-13-53](https://user-images.githubusercontent.com/1816969/35399694-8656ee6e-01fd-11e8-8e10-cd534e4ee879.png)

**So from where does the text get its color?**

**Comment by PaulKinlan** [comment]
Chrome works out the colour based on what contrasts well.
