### ISSUE TITLE
How beforeinstallprompt event is fired every time the browser refresh?

### ISSUE THREAD

**Issue by anshuPurohit** [GoogleChromeLabs/airhorn#46]
Google docs says it will be called only once in 3 months.
If dismissed by a user, it will not be shown until a sufficient period of time (~3 months) has passed.

https://developers.google.com/web/updates/2018/06/a2hs-updates

const beforeinstallprompt = function(e) {
    promptEvent = e;
    promptEvent.preventDefault();
    ga('send', 'event', 'install', 'available');
    root.classList.add('available');
    return false;
  };
  

  window.addEventListener('beforeinstallprompt', beforeinstallprompt);

**Comment by PaulKinlan** [comment]
Did you dismiss it once you pressed the install button?
